services:
  web:
    build: .
    container_name: lotto_web_32220623
    command: gunicorn lotto_site.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: lotto_nginx_32220623
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: lotto_postgres_32220623
    environment:
      POSTGRES_DB: lotto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
