services:
  web:
    build: .
    container_name: django_lotto_32220623
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DB_NAME=lotto
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres:15
    container_name: postgres_lotto_32220623
    restart: always
    environment:
      POSTGRES_DB: lotto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
